theme: jekyll-theme-slate

# サイト情報
title: Yoshio Takaeda | Portfolio
description: Forward Deploy Engineer / Data Architect / Researcher / Lecturer
lang: ja

# SEO
author: Yoshio Takaeda
url: https://takaeda.is-a.dev

# Markdown設定
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# 除外ファイル
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
